# Generated by Django 5.2.6 on 2025-09-17 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='greenwashtext',
            old_name='name',
            new_name='text',
        ),
    ]
