# Generated by Django 5.2.6 on 2025-10-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_name_greenwashtext_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('score', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='GreenwashText',
        ),
    ]
